import {useEffect,useMemo,useState} from 'react';
import './App.css';
import {getTransactions} from './services/api';
const groups=[['DASHBOARD',['Dashboard Bulanan','Dashboard Tahunan','Perbandingan Tahunan']],['MANAJEMEN',['Input Transaksi','Riwayat Transaksi','Transfer Saldo Bank','Transaksi Rutin','Kalender Keuangan']],['BUDGET ANGGARAN',['Budget Anggaran','Target Keuangan','Laporan Keuangan']],['KEUANGAN',['Hutang','Piutang','Saldo Bank','Cross Check Saldo','Kekayaan Bersih']],['SISTEM',['Konsultasi','Pengaturan']]];
const icons=['▦','▥','⌁','＋','↻','⇄','⟳','□','▤','◎','▣','▣','♧','▤','⇆','◆','◌','⚙'];
const fmt=new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0});
function App(){const[active,setActive]=useState('Dashboard Bulanan');const[data,setData]=useState([]);const[loading,setLoading]=useState(true);const[error,setError]=useState('');useEffect(()=>{getTransactions().then(x=>setData(Array.isArray(x.data)?x.data:[])).catch(e=>setError(e.message)).finally(()=>setLoading(false))},[]);const stats=useMemo(()=>{let income=0,expense=0;data.forEach(t=>{const n=Number(t.amount||0);if(String(t.type).toLowerCase()==='income')income+=n;if(String(t.type).toLowerCase()==='expense')expense+=n});return{income,expense,net:income-expense}},[data]);return <div className="app"><aside className="sidebar"><div className="brand"><div className="logo">MT</div><div><b>MONEY</b><strong>TRACKING</strong></div></div><div className="sub">SMART FINANCIAL MANAGEMENT</div><nav>{groups.map(([title,items],gi)=><section key={title}><h4>{title}</h4>{items.map((item,i)=>{const idx=groups.slice(0,gi).reduce((a,g)=>a+g[1].length,0)+i;return <button key={item} className={active===item?'active':''} onClick={()=>setActive(item)}><span>{icons[idx]}</span>{item}{active===item&&<em/>}</button>})}</section>)}</nav><div className="foot"><div className="sync">↕ <div><small>DATA</small><b>Langsung</b></div><i>● Online</i></div><div className="user"><span>KY</span><div><b>KY</b><small>SUPER MASTER</small></div>›</div></div></aside><main><header><div><small>MONEY TRACKING</small><h1>{active}</h1></div><div className="head"><button>◐</button><button>♢</button><b>KY</b><small>SUPER MASTER</small></div></header>{active==='Dashboard Bulanan'?<Dashboard data={data} loading={loading} error={error} stats={stats} go={setActive}/>:<div className="placeholder"><div>◈</div><small>MONEY TRACKING</small><h2>{active}</h2><p>Modul ini akan kita bangun dan hubungkan ke database.</p><button onClick={()=>setActive('Dashboard Bulanan')}>← Dashboard</button></div>}</main></div>}
function Dashboard({data,loading,error,stats,go}){return <div className="dashboard"><div className="hero"><div><small>FINANCIAL OVERVIEW</small><h2>Selamat datang kembali, <b>KY</b></h2><p>Pantau kondisi keuangan kamu dalam satu tampilan.</p></div><div className="period"><small>PERIODE AKTIF</small><b>September 2026</b><span>Bulan ini ▾</span></div></div>{error&&<div className="warning"><b>API belum tersambung</b> {error}</div>}<div className="balance"><div><small>TOTAL SALDO</small><strong>{fmt.format(stats.net)}</strong><span>↗ 0% dari bulan sebelumnya</span></div><div className="meta"><div><small>REKENING AKTIF</small><b>0</b></div><div><small>TRANSAKSI BULAN INI</small><b>{data.length}</b></div></div></div><div className="stats"><Stat t="PEMASUKAN" v={stats.income} c="green"/><Stat t="PENGELUARAN" v={stats.expense} c="red"/><Stat t="HUTANG" v={0} c="gold"/><Stat t="KEKAYAAN BERSIH" v={stats.net} c="blue"/></div><div className="quick"><div><small>AKSI CEPAT</small><b>Kelola keuangan</b></div><div><button className="primary" onClick={()=>go('Input Transaksi')}>＋ Tambah Transaksi</button><button onClick={()=>go('Transfer Saldo Bank')}>⇄ Transfer</button><button onClick={()=>go('Saldo Bank')}>▤ Saldo Bank</button></div></div><div className="grid"><div className="card"><Head a="ANALISIS KEUANGAN" t="Arus Kas"/><div className="chart"><div className="yl"><span>Rp 5jt</span><span>Rp 4jt</span><span>Rp 3jt</span><span>Rp 2jt</span><span>Rp 1jt</span><span>Rp 0</span></div><div className="area">{[17,34,51,68,85].map(x=><i key={x} style={{top:x+'%'}}/>)}<div className="empty"><b>↗</b><strong>{loading?'Mengambil data...':data.length?`${data.length} transaksi ditemukan`:'Belum ada data'}</strong><span>{data.length?'Data berasal dari MONEY TRACKING API.':'Tambahkan transaksi untuk melihat arus kas.'}</span></div><div className="months">{['Apr','Mei','Jun','Jul','Agu','Sep'].map(x=><span key={x}>{x}</span>)}</div></div></div></div><div className="card"><Head a="AKTIVITAS" t="Transaksi Terbaru" action={()=>go('Riwayat Transaksi')}/><div className="txs">{data.slice(0,6).map((t,i)=><div className="tx" key={t.id||i}><b>{String(t.type).toLowerCase()==='income'?'↗':'↘'}</b><div><strong>{t.description||t.category_id||'Transaksi'}</strong><small>{t.date||'-'}</small></div><span>{fmt.format(Number(t.amount||0))}</span></div>)}{!data.length&&<div className="empty"><b>◎</b><strong>{loading?'Mengambil data...':'Belum ada transaksi'}</strong><span>Data akan muncul otomatis dari API.</span></div>}</div></div></div><div className="bottom"><Mini a="ANGGARAN" t="Budget Bulanan" x="Belum ada budget"/><Mini a="TARGET" t="Target Keuangan" x="Belum ada target keuangan"/><Mini a="SALDO BANK" t="Rekening" x="0 rekening aktif"/></div></div>}
function Stat({t,v,c}){return <div className="stat"><div><small>{t}</small><b className={c}>{c==='green'?'↗':c==='red'?'↘':c==='gold'?'−':'◆'}</b></div><strong>{fmt.format(v)}</strong><span>0% vs bulan lalu</span></div>}
function Head({a,t,action}){return <div className="cardhead"><div><small>{a}</small><h3>{t}</h3></div>{action&&<button onClick={action}>Lihat semua →</button>}</div>}
function Mini({a,t,x}){return <div className="card mini"><div className="cardhead"><div><small>{a}</small><h3>{t}</h3></div><b>→</b></div><p>{x}</p></div>}
export default App;
